USE [SIS_TECH]
GO

begin tran
 
 --rollback
 --commit
-- select * from Cnae 
insert into Cnae values('3250706','Serviços de prótese dentária','V',1, 	15.5	 )
insert into Cnae values('3250706','Serviços de prótese dentária','III',1, 	6	 )
insert into Cnae values('3250709','Serviço de laboratório óptico','V',1, 	15.5	 )
insert into Cnae values('3250709','Serviço de laboratório óptico','III',1, 	6	 )
insert into Cnae values('4399101','Administração de obras','III',0, 	6	 )
insert into Cnae values('4512901','Representantes comerciais e agentes do comércio de veículos automotores','V',1, 	15.5	 )
insert into Cnae values('4530702','Comércio por atacado de pneumáticos e câmaras-de-ar','I',0, 	4	 )
insert into Cnae values('4530703','Comércio a varejo de peças e acessórios novos para veículos automotores','I',0, 	4	 )
insert into Cnae values('4530704','Comércio a varejo de peças e acessórios usados para veículos automotores','I',0, 	4	 )
insert into Cnae values('4530705','Comércio a varejo de pneumáticos e câmaras-de-ar','I',0, 	4	 )
insert into Cnae values('4530706','Representantes comerciais e agentes do comércio de peças e acessórios novos e usados para veículos automotores','V',1, 	15.5	 )
insert into Cnae values('4541202','Comércio por atacado de peças e acessórios para motocicletas e motonetas','I',0, 	4	 )
insert into Cnae values('4541206','Comércio a varejo de peças e acessórios novos para motocicletas e motonetas','I',0, 	4	 )
insert into Cnae values('4541207','Comércio a varejo de peças e acessórios usados para motocicletas e motonetas','I',0, 	4	 )
insert into Cnae values('4542101','Representantes comerciais e agentes do comércio de motocicletas e motonetas, peças e acessórios','V',1, 	15.5	 )
insert into Cnae values('4611700','Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos','V',1, 	15.5	 )
insert into Cnae values('4612500','Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos','V',1, 	15.5	 )
insert into Cnae values('4613300','Representantes comerciais e agentes do comércio de madeira, material de construção e ferragens','V',1, 	15.5	 )
insert into Cnae values('4614100','Representantes comerciais e agentes do comércio de máquinas, equipamentos, embarcações e aeronaves','V',1, 	15.5	 )
insert into Cnae values('4615000','Representantes comerciais e agentes do comércio de eletrodomésticos, móveis e artigos de uso doméstico','V',1, 	15.5	 )
insert into Cnae values('4616800','Representantes comerciais e agentes do comércio de têxteis, vestuário, calçados e artigos de viagem','V',1, 	15.5	 )
insert into Cnae values('4617600','Representantes comerciais e agentes do comércio de produtos alimentícios, bebidas e fumo','V',1, 	15.5	 )
insert into Cnae values('4618401','Representantes comerciais e agentes do comércio de medicamentos, cosméticos e produtos de perfumaria','V',1, 	15.5	 )
insert into Cnae values('4618402','Representantes comerciais e agentes do comércio de instrumentos e materiais odonto-médico-hospitalares','V',1, 	15.5	 )
insert into Cnae values('4618403','Representantes comerciais e agentes do comércio de jornais, revistas e outras publicações','V',1, 	15.5	 )
insert into Cnae values('4618499','Outros representantes comerciais e agentes do comércio especializado em produtos não especificados anteriormente','V',1, 	15.5	 )
insert into Cnae values('4619200','Representantes comerciais e agentes do comércio de mercadorias em geral não especializado','V',1, 	15.5	 )
insert into Cnae values('4711301','Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios – hipermercados','I',0, 	4	 )
insert into Cnae values('4711302','Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios – supermercados','I',0, 	4	 )
insert into Cnae values('4712100','Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios – minimercados, mercearias e armazéns','I',0, 	4	 )
insert into Cnae values('4713002','Lojas de variedades, exceto lojas de departamentos ou magazines','I',0, 	4	 )
insert into Cnae values('4713004','Lojas de departamentos ou magazines, exceto lojas francas (Duty free)','I',0, 	4	 )
insert into Cnae values('4721102','Padaria e confeitaria com predominância de revenda','I',0, 	4	 )
insert into Cnae values('4721103','Comércio varejista de laticínios e frios','I',0, 	4	 )
insert into Cnae values('4721104','Comércio varejista de doces, balas, bombons e semelhantes','I',0, 	4	 )
insert into Cnae values('4723700','Comércio varejista de bebidas','I',0, 	4	 )
insert into Cnae values('4724500','Comércio varejista de hortifrutigranjeiros','I',0, 	4	 )
insert into Cnae values('4729601','Tabacaria','I',0, 	4	 )
insert into Cnae values('4729699','Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente','I',0, 	4	 )
insert into Cnae values('4743100','Comércio varejista de vidros','I',0, 	4	 )
insert into Cnae values('4744002','Comércio varejista de madeira e artefatos','I',0, 	4	 )
insert into Cnae values('4751201','Comércio varejista especializado de equipamentos e suprimentos de informática','I',0, 	4	 )
insert into Cnae values('4751202','Recarga de cartuchos para equipamentos de informática','III',0, 	6	 )
insert into Cnae values('4752100','Comércio varejista especializado de equipamentos de telefonia e comunicação','I',0, 	4	 )
insert into Cnae values('4753900','Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo','I',0, 	4	 )
insert into Cnae values('4754701','Comércio varejista de móveis','I',0, 	4	 )
insert into Cnae values('4754702','Comércio varejista de artigos de colchoaria','I',0, 	4	 )
insert into Cnae values('4754703','Comércio varejista de artigos de iluminação','I',0, 	4	 )
insert into Cnae values('4755501','Comércio varejista de tecidos','I',0, 	4	 )
insert into Cnae values('4755502','Comércio varejista de artigos de armarinho','I',0, 	4	 )
insert into Cnae values('4755503','Comércio varejista de artigos de cama, mesa e banho','I',0, 	4	 )
insert into Cnae values('4756300','Comércio varejista especializado de instrumentos musicais e acessórios','I',0, 	4	 )
insert into Cnae values('4757100','Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação','I',0, 	4	 )
insert into Cnae values('4759801','Comércio varejista de artigos de tapeçaria, cortinas e persianas','I',0, 	4	 )
insert into Cnae values('4759899','Comércio varejista de outros artigos de uso doméstico não especificados anteriormente','I',0, 	4	 )
insert into Cnae values('4761001','Comércio varejista de livros','I',0, 	4	 )
insert into Cnae values('4761002','Comércio varejista de jornais e revistas','I',0, 	4	 )
insert into Cnae values('4761003','Comércio varejista de artigos de papelaria','I',0, 	4	 )
insert into Cnae values('4762800','Comércio varejista de discos, CDs, DVDs e fitas','I',0, 	4	 )
insert into Cnae values('4763601','Comércio varejista de brinquedos e artigos recreativos','I',0, 	4	 )
insert into Cnae values('4763602','Comércio varejista de artigos esportivos','I',0, 	4	 )
insert into Cnae values('4763603','Comércio varejista de bicicletas e triciclos peças e acessórios','I',0, 	4	 )
insert into Cnae values('4763604','Comércio varejista de artigos de caça, pesca e camping','I',0, 	4	 )
insert into Cnae values('4772500','Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal','I',0, 	4	 )
insert into Cnae values('4774100','Comércio varejista de artigos de óptica','I',0, 	4	 )
insert into Cnae values('4781400','Comércio varejista de artigos do vestuário e acessórios','I',0, 	4	 )
insert into Cnae values('4782201','Comércio varejista de calçados','I',0, 	4	 )
insert into Cnae values('4782202','Comércio varejista de artigos de viagem','I',0, 	4	 )
insert into Cnae values('4783102','Comércio varejista de artigos de relojoaria','I',0, 	4	 )
insert into Cnae values('4785701','Comércio varejista de antigüidades','I',0, 	4	 )
insert into Cnae values('4785799','Comércio varejista de outros artigos usados','I',0, 	4	 )
insert into Cnae values('4789001','Comércio varejista de suvenires, bijuterias e artesanatos','I',0, 	4	 )
insert into Cnae values('4789002','Comércio varejista de plantas e flores naturais','I',0, 	4	 )
insert into Cnae values('4789003','Comércio varejista de objetos de arte','I',0, 	4	 )
insert into Cnae values('4789007','Comércio varejista de equipamentos para escritório','I',0, 	4	 )
insert into Cnae values('4789008','Comércio varejista de artigos fotográficos e para filmagem','I',0, 	4	 )
insert into Cnae values('4789099','Comércio varejista de outros produtos não especificados anteriormente','I',0, 	4	 )
insert into Cnae values('5611201','Restaurantes e similares','I',0, 	4	 )
insert into Cnae values('5611203','Lanchonetes, casas de chá, de sucos e similares','I',0, 	4	 )
insert into Cnae values('5611204','Bares e outros estabelecimentos especializados em servir bebidas, sem entretenimento','I',0, 	4	 )
insert into Cnae values('5620101','Fornecimento de alimentos preparados preponderantemente para empresas','I',0, 	4	 )
insert into Cnae values('5620103','Cantinas – serviços de alimentação privativos','I',0, 	4	 )
insert into Cnae values('5620104','Fornecimento de alimentos preparados preponderantemente para consumo domiciliar','I',0, 	4	 )
insert into Cnae values('5911101','Estúdios cinematográficos','III',0, 	6	 )
insert into Cnae values('5911102','Produção de filmes para publicidade','III',0, 	6	 )
insert into Cnae values('5911199','Atividades de produção cinematográfica, de vídeos e de programas de televisão não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('5912001','Serviços de dublagem','III',0, 	6	 )
insert into Cnae values('5912002','Serviços de mixagem sonora em produção audiovisual','III',0, 	6	 )
insert into Cnae values('5912099','Atividades de pós-produção cinematográfica, de vídeos e de programas de televisão não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('5913800','Distribuição cinematográfica, de vídeo e de programas de televisão','III',0, 	6	 )
insert into Cnae values('5914600','Atividades de exibição cinematográfica','III',0, 	6	 )
insert into Cnae values('5920100','Atividades de gravação de som e de edição de música','III',0, 	6	 )
insert into Cnae values('6201501','Desenvolvimento de programas de computador sob encomenda','V',1, 	15.5	 )
insert into Cnae values('6201501','Desenvolvimento de programas de computador sob encomenda','III',1, 	6	 )
insert into Cnae values('6201502','Web design','V',1, 	15.5	 )
insert into Cnae values('6201502','Web design','III',1, 	6	 )
insert into Cnae values('6202300','Desenvolvimento e licenciamento de programas de computador customizáveis','V',1, 	15.5	 )
insert into Cnae values('6202300','Desenvolvimento e licenciamento de programas de computador customizáveis','III',1, 	6	 )
insert into Cnae values('6203100','Desenvolvimento e licenciamento de programas de computador não-customizáveis','V',1, 	15.5	 )
insert into Cnae values('6203100','Desenvolvimento e licenciamento de programas de computador não-customizáveis','III',1, 	6	 )
insert into Cnae values('6204000','Consultoria em tecnologia da informação','V',1, 	15.5	 )
insert into Cnae values('6209100','Suporte técnico, manutenção e outros serviços em tecnologia da informação','V',1, 	15.5	 )
insert into Cnae values('6209100','Suporte técnico, manutenção e outros serviços em tecnologia da informação','III',1, 	6	 )
insert into Cnae values('6311900','Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet','V',1, 	15.5	 )
insert into Cnae values('6311900','Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet','III',1, 	6	 )
insert into Cnae values('6319400','Portais, provedores de conteúdo e outros serviços de informação na internet','V',1, 	15.5	 )
insert into Cnae values('6319400','Portais, provedores de conteúdo e outros serviços de informação na internet','III',1, 	6	 )
insert into Cnae values('6391700','Agências de notícias','III',0, 	6	 )
insert into Cnae values('6399200','Outras atividades de prestação de serviços de informação não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('6619302','Correspondentes de instituições financeiras','III',0, 	6	 )
insert into Cnae values('6621501','Peritos e avaliadores de seguros','V',1, 	15.5	 )
insert into Cnae values('6621502','Auditoria e consultoria atuarial','V',1, 	15.5	 )
insert into Cnae values('6622300','Corretores e agentes de seguros, de planos de previdência complementar e de saúde','III',0, 	6	 )
insert into Cnae values('6629100','Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('6821801','Corretagem na compra e venda e avaliação de imóveis','III',0, 	6	 )
insert into Cnae values('6821802','Corretagem no aluguel de imóveis','III',0, 	6	 )
insert into Cnae values('6911701','Serviços advocatícios','IV',0, 	4.5	 )
insert into Cnae values('6911703','Agente de propriedade industrial','V',1, 	15.5	 )
insert into Cnae values('7020400','Atividades de consultoria em gestão empresarial, exceto consultoria técnica específica','V',1, 	15.5	 )
insert into Cnae values('7111100','Serviços de arquitetura','III',1, 	6	 )
insert into Cnae values('7112000','Serviços de engenharia','V',1, 	15.5	 )
insert into Cnae values('7119701','Serviços de cartografia, topografia e geodésia','V',1, 	15.5	 )
insert into Cnae values('7119702','Atividades de estudos geológicos','V',1, 	15.5	 )
insert into Cnae values('7119703','Serviços de desenho técnico relacionados à arquitetura e engenharia','V',1, 	15.5	 )
insert into Cnae values('7119704','Serviços de perícia técnica relacionados à segurança do trabalho','V',1, 	15.5	 )
insert into Cnae values('7119799','Atividades técnicas relacionadas à engenharia e arquitetura não especificadas anteriormente','V',1, 	15.5	 )
insert into Cnae values('7120100','Testes e análises técnicas','V',1, 	15.5	 )
insert into Cnae values('7210000','Pesquisa e desenvolvimento experimental em ciências físicas e naturais','V',1, 	15.5	 )
insert into Cnae values('7220700','Pesquisa e desenvolvimento experimental em ciências sociais e humanas','V',1, 	15.5	 )
insert into Cnae values('7311400','Agências de publicidade','V',1, 	15.5	 )
insert into Cnae values('7312200','Agenciamento de espaços para publicidade exceto em veículos de comunicação','III',0, 	6	 )
insert into Cnae values('7319001','Criação de estandes para feiras e exposições','V',1, 	15.5	 )
insert into Cnae values('7319002','Promoção de vendas','III',0, 	6	 )
insert into Cnae values('7319003','Marketing direto','III',0, 	6	 )
insert into Cnae values('7319004','Consultoria em publicidade','V',1, 	15.5	 )
insert into Cnae values('7319099','Outras atividades de publicidade não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('7320300','Pesquisas de mercado e de opinião pública','V',1, 	15.5	 )
insert into Cnae values('7410202','Design de interiores','V',1, 	15.5	 )
insert into Cnae values('7410202','Design de interiores','IV',1, 	4.5	 )
insert into Cnae values('7410203','Design de produto','V',1, 	15.5	 )
insert into Cnae values('7410299','Atividades de design não especificadas anteriormente','V',1, 	15.5	 )
insert into Cnae values('7420001','Atividades de produção de fotografias, exceto aérea e submarina','III',0, 	6	 )
insert into Cnae values('7420002','Atividades de produção de fotografias aéreas e submarinas','III',0, 	6	 )
insert into Cnae values('7420003','Laboratórios fotográficos','III',0, 	6	 )
insert into Cnae values('7420004','Filmagem de festas e eventos','III',0, 	6	 )
insert into Cnae values('7420005','Serviços de microfilmagem','III',0, 	6	 )
insert into Cnae values('7490101','Serviços de tradução, interpretação e similares','V',1, 	15.5	 )
insert into Cnae values('7490102','Escafandria e mergulho','III',0, 	6	 )
insert into Cnae values('7490103','Serviços de agronomia e de consultoria às atividades agrícolas e pecuárias','V',1, 	15.5	 )
insert into Cnae values('7490104','Atividades de intermediação e agenciamento de serviços e negócios em geral, exceto imobiliários','V',1, 	15.5	 )
insert into Cnae values('7490105','Agenciamento de profissionais para atividades esportivas, culturais e artísticas','V',1, 	15.5	 )
insert into Cnae values('7490199','Outras atividades profissionais, científicas e técnicas não especificadas anteriormente','V',1, 	15.5	 )
insert into Cnae values('7500100','Atividades veterinárias','V',1, 	15.5	 )
insert into Cnae values('7721700','Aluguel de equipamentos recreativos e esportivos','III',0, 	6	 )
insert into Cnae values('7722500','Aluguel de fitas de vídeo, DVDs e similares','III',0, 	6	 )
insert into Cnae values('7723300','Aluguel de objetos do vestuário, jóias e acessórios','III',0, 	6	 )
insert into Cnae values('7729201','Aluguel de aparelhos de jogos eletrônicos','III',0, 	6	 )
insert into Cnae values('7729202','Aluguel de móveis, utensílios e aparelhos de uso doméstico e pessoal; instrumentos musicais','III',0, 	6	 )
insert into Cnae values('7729203','Aluguel de material médico','III',0, 	6	 )
insert into Cnae values('7729299','Aluguel de outros objetos pessoais e domésticos não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('7731400','Aluguel de máquinas e equipamentos agrícolas sem operador','III',0, 	6	 )
insert into Cnae values('7732201','Aluguel de máquinas e equipamentos para construção sem operador, exceto andaimes','III',0, 	6	 )
insert into Cnae values('7732202','Aluguel de andaimes','III',0, 	6	 )
insert into Cnae values('7733100','Aluguel de máquinas e equipamentos para escritório','III',0, 	6	 )
insert into Cnae values('7739001','Aluguel de máquinas e equipamentos para extração de minérios e petróleo, sem operador','III',0, 	6	 )
insert into Cnae values('7739002','Aluguel de equipamentos científicos, médicos e hospitalares, sem operador','III',0, 	6	 )
insert into Cnae values('7739003','Aluguel de palcos, coberturas e outras estruturas de uso temporário, exceto andaimes','III',0, 	6	 )
insert into Cnae values('7739099','Aluguel de outras máquinas e equipamentos comerciais e industriais não especificados anteriormente, sem operador','III',0, 	6	 )
insert into Cnae values('7740300','Gestão de ativos intangíveis não-financeiros','V',1, 	15.5	 )
insert into Cnae values('7911200','Agências de viagens','III',0, 	6	 )
insert into Cnae values('7912100','Operadores turísticos','III',0, 	6	 )
insert into Cnae values('7990200','Serviços de reservas e outros serviços de turismo não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('8011102','Serviços de adestramento de cães de guarda','III',0, 	6	 )
insert into Cnae values('8030700','Atividades de investigação particular','V',1, 	15.5	 )
insert into Cnae values('8121400','Limpeza em prédios e em domicílios','IV',0, 	4.5	 )
insert into Cnae values('8122200','Imunização e controle de pragas urbanas','IV',0, 	4.5	 )
insert into Cnae values('8129000','Atividades de limpeza não especificadas anteriormente','IV',0, 	4.5	 )
insert into Cnae values('8130300','Atividades paisagísticas','IV',0, 	4.5	 )
insert into Cnae values('8211300','Serviços combinados de escritório e apoio administrativo','III',0, 	6	 )
insert into Cnae values('8219999','Preparação de documentos e serviços especializados de apoio administrativo não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('8220200','Atividades de teleatendimento','III',0, 	6	 )
insert into Cnae values('8230001','Serviços de organização de feiras, congressos, exposições e festas','III',0, 	6	 )
insert into Cnae values('8230002','Casas de festas e eventos','III',0, 	6	 )
insert into Cnae values('8291100','Atividades de cobrança e informações cadastrais','III',0, 	6	 )
insert into Cnae values('8299701','Medição de consumo de energia elétrica, gás e água','III',0, 	6	 )
insert into Cnae values('8299703','Serviços de gravação de carimbos, exceto confecção','III',0, 	6	 )
insert into Cnae values('8299707','Salas de acesso à internet','III',0, 	6	 )
insert into Cnae values('8299799','Outras atividades de serviços prestados principalmente às empresas não especificadas anteriormente','V',1, 	15.5	 )
insert into Cnae values('8299799','Outras atividades de serviços prestados principalmente às empresas não especificadas anteriormente','III',1, 	6	 )
insert into Cnae values('8511200','Educação infantil – creche','III',0, 	6	 )
insert into Cnae values('8512100','Educação infantil – pré-escola','III',0, 	6	 )
insert into Cnae values('8513900','Ensino fundamental','III',0, 	6	 )
insert into Cnae values('8520100','Ensino médio','III',0, 	6	 )
insert into Cnae values('8531700','Educação superior – graduação','V',1, 	15.5	 )
insert into Cnae values('8532500','Educação superior – graduação e pós-graduação','V',1, 	15.5	 )
insert into Cnae values('8533300','Educação superior – pós-graduação e extensão','V',1, 	15.5	 )
insert into Cnae values('8541400','Educação profissional de nível técnico','III',0, 	6	 )
insert into Cnae values('8542200','Educação profissional de nível tecnológico','V',1, 	15.5	 )
insert into Cnae values('8550302','Atividades de apoio à educação, exceto caixas escolares','V',1, 	15.5	 )
insert into Cnae values('8591100','Ensino de esportes','V',1, 	15.5	 )
insert into Cnae values('8591100','Ensino de esportes','III',1, 	6	 )
insert into Cnae values('8592901','Ensino de dança','V',1, 	15.5	 )
insert into Cnae values('8592901','Ensino de dança','III',1, 	6	 )
insert into Cnae values('8592902','Ensino de artes cênicas, exceto dança','III',0, 	6	 )
insert into Cnae values('8592903','Ensino de música','III',0, 	6	 )
insert into Cnae values('8592999','Ensino de arte e cultura não especificado anteriormente','III',0, 	6	 )
insert into Cnae values('8593700','Ensino de idiomas','III',0, 	6	 )
insert into Cnae values('8599603','Treinamento em informática','III',0, 	6	 )
insert into Cnae values('8599604','Treinamento em desenvolvimento profissional e gerencial','III',0, 	6	 )
insert into Cnae values('8599605','Cursos preparatórios para concursos','III',0, 	6	 )
insert into Cnae values('8599699','Outras atividades de ensino não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('8610101','Atividades de atendimento hospitalar, exceto pronto-socorro e unidades para atendimento a urgências','III',1, 	6	 )
insert into Cnae values('8630501','Atividade médica ambulatorial com recursos para realização de procedimentos cirúrgicos','III',1, 	6	 )
insert into Cnae values('8630502','Atividade médica ambulatorial com recursos para realização de exames complementares','III',1, 	6	 )
insert into Cnae values('8630503','Atividade médica ambulatorial restrita a consultas','III',1, 	6	 )
insert into Cnae values('8630504','Atividade odontológica','III',1, 	6	 )
insert into Cnae values('8630506','Serviços de vacinação e imunização humana','III',1, 	6	 )
insert into Cnae values('8630507','Atividades de reprodução humana assistida','III',1, 	6	 )
insert into Cnae values('8630599','Atividades de atenção ambulatorial não especificadas anteriormente','III',1, 	6	 )
insert into Cnae values('8640201','Laboratórios de anatomia patológica e citológica','V',1, 	15.5	 )
insert into Cnae values('8640201','Laboratórios de anatomia patológica e citológica','III',1, 	6	 )
insert into Cnae values('8640202','Laboratórios clínicos','V',1, 	15.5	 )
insert into Cnae values('8640202','Laboratórios clínicos','III',1, 	6	 )
insert into Cnae values('8640203','Serviços de diálise e nefrologia','III',1, 	6	 )
insert into Cnae values('8640204','Serviços de tomografia','V',1, 	15.5	 )
insert into Cnae values('8640204','Serviços de tomografia','III',1, 	6	 )
insert into Cnae values('8640205','Serviços de diagnóstico por imagem com uso de radiação ionizante, exceto tomografia','V',1, 	15.5	 )
insert into Cnae values('8640205','Serviços de diagnóstico por imagem com uso de radiação ionizante, exceto tomografia','III',1, 	6	 )
insert into Cnae values('8640206','Serviços de ressonância magnética','V',1, 	15.5	 )
insert into Cnae values('8640206','Serviços de ressonância magnética','III',1, 	6	 )
insert into Cnae values('8640207','Serviços de diagnóstico por imagem sem uso de radiação ionizante, exceto ressonância magnética','V',1, 	15.5	 )
insert into Cnae values('8640207','Serviços de diagnóstico por imagem sem uso de radiação ionizante, exceto ressonância magnética','III',1, 	6	 )
insert into Cnae values('8640208','Serviços de diagnóstico por registro gráfico – ECG, EEG e outros exames análogos','V',1, 	15.5	 )
insert into Cnae values('8640208','Serviços de diagnóstico por registro gráfico – ECG, EEG e outros exames análogos','III',1, 	6	 )
insert into Cnae values('8640209','Serviços de diagnóstico por métodos ópticos – endoscopia e outros exames análogos','V',1, 	15.5	 )
insert into Cnae values('8640209','Serviços de diagnóstico por métodos ópticos – endoscopia e outros exames análogos','III',1, 	6	 )
insert into Cnae values('8640210','Serviços de quimioterapia','III',1, 	6	 )
insert into Cnae values('8640211','Serviços de radioterapia','III',1, 	6	 )
insert into Cnae values('8640212','Serviços de hemoterapia','III',1, 	6	 )
insert into Cnae values('8640213','Serviços de litotripsia','III',1, 	6	 )
insert into Cnae values('8640214','Serviços de bancos de células e tecidos humanos','III',1, 	6	 )
insert into Cnae values('8640299','Atividades de serviços de complementação diagnóstica e terapêutica não especificadas anteriormente','III',1, 	6	 )
insert into Cnae values('8650001','Atividades de enfermagem','III',1, 	6	 )
insert into Cnae values('8650002','Atividades de profissionais da nutrição','III',1, 	6	 )
insert into Cnae values('8650003','Atividades de psicologia e psicanálise','III',1, 	6	 )
insert into Cnae values('8650004','Atividades de fisioterapia','III',1, 	6	 )
insert into Cnae values('8650004','Atividades de fisioterapia','III',1, 	6	 )
insert into Cnae values('8650005','Atividades de terapia ocupacional','III',1, 	6	 )
insert into Cnae values('8650006','Atividades de fonoaudiologia','III',1, 	6	 )
insert into Cnae values('8650007','Atividades de terapia de nutrição enteral e parenteral','V',1, 	15.5	 )
insert into Cnae values('8650099','Atividades de profissionais da área de saúde não especificadas anteriormente','V',1, 	15.5	 )
insert into Cnae values('8660700','Atividades de apoio à gestão de saúde','V',1, 	15.5	 )
insert into Cnae values('8690901','Atividades de práticas integrativas e complementares em saúde humana','V',1, 	15.5	 )
insert into Cnae values('8690903','Atividades de acupuntura','III',1, 	6	 )
insert into Cnae values('8690904','Atividades de podologia','III',1, 	6	 )
insert into Cnae values('8690999','Outras atividades de atenção à saúde humana não especificadas anteriormente','V',1, 	15.5	 )
insert into Cnae values('9001901','Produção teatral','III',0, 	6	 )
insert into Cnae values('9001902','Produção musical','III',0, 	6	 )
insert into Cnae values('9001903','Produção de espetáculos de dança','III',0, 	6	 )
insert into Cnae values('9001904','Produção de espetáculos circenses, de marionetes e similares','III',0, 	6	 )
insert into Cnae values('9001905','Produção de espetáculos de rodeios, vaquejadas e similares','III',0, 	6	 )
insert into Cnae values('9001906','Atividades de sonorização e de iluminação','III',0, 	6	 )
insert into Cnae values('9001999','Artes cênicas, espetáculos e atividades complementares não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('9002701','Atividades de artistas plásticos, jornalistas independentes e escritores','V',1, 	15.5	 )
insert into Cnae values('9002702','Restauração de obras de arte','III',0, 	6	 )
insert into Cnae values('9311500','Gestão de instalações de esportes','III',0, 	6	 )
insert into Cnae values('9313100','Atividades de condicionamento físico','V',1, 	15.5	 )
insert into Cnae values('9313100','Atividades de condicionamento físico','III',1, 	6	 )
insert into Cnae values('9319101','Produção e promoção de eventos esportivos','III',0, 	6	 )
insert into Cnae values('9319199','Outras atividades esportivas não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('9329802','Exploração de boliches','III',0, 	6	 )
insert into Cnae values('9329803','Exploração de jogos de sinuca, bilhar e similares','III',0, 	6	 )
insert into Cnae values('9329804','Exploração de jogos eletrônicos recreativos','III',0, 	6	 )
insert into Cnae values('9329899','Outras atividades de recreação e lazer não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('9511800','Reparação e manutenção de computadores e de equipamentos periféricos','III',0, 	6	 )
insert into Cnae values('9512600','Reparação e manutenção de equipamentos de comunicação','III',0, 	6	 )
insert into Cnae values('9521500','Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico','III',0, 	6	 )
insert into Cnae values('9529101','Reparação de calçados, bolsas e artigos de viagem','III',0, 	6	 )
insert into Cnae values('9529102','Chaveiros','III',0, 	6	 )
insert into Cnae values('9529103','Reparação de relógios','III',0, 	6	 )
insert into Cnae values('9529104','Reparação de bicicletas, triciclos e outros veículos não-motorizados','III',0, 	6	 )
insert into Cnae values('9529105','Reparação de artigos do mobiliário','III',0, 	6	 )
insert into Cnae values('9529106','Reparação de jóias','III',0, 	6	 )
insert into Cnae values('9529199','Reparação e manutenção de outros objetos e equipamentos pessoais e domésticos não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('9601701','Lavanderias','III',0, 	6	 )
insert into Cnae values('9601702','Tinturarias','III',0, 	6	 )
insert into Cnae values('9601703','Toalheiros','III',0, 	6	 )
insert into Cnae values('9602501','Cabeleireiros, manicure e pedicure','III',0, 	6	 )
insert into Cnae values('9602502','Atividades de Estética e outros serviços de cuidados com a beleza','III',0, 	6	 )
insert into Cnae values('9609202','Agências matrimoniais','III',0, 	6	 )
insert into Cnae values('9609205','Atividades de sauna e banhos','III',0, 	6	 )
insert into Cnae values('9609206','Serviços de tatuagem e colocação de piercing','III',0, 	6	 )
insert into Cnae values('9609207','Alojamento de animais domésticos','III',0, 	6	 )
insert into Cnae values('9609208','Higiene e embelezamento de animais domésticos','III',0, 	6	 )
insert into Cnae values('9609299','Outras atividades de serviços pessoais não especificadas anteriormente','III',0, 	6	 )
insert into Cnae values('161003','Serviço de preparação de terreno, cultivo e colheita','III',0, 	6	 )
insert into Cnae values('162803','Serviço de manejo de animais','III',0, 	6	 )
insert into Cnae values('322107','Atividades de apoio à aqüicultura em água doce','III',0, 	6	 )
insert into Cnae values('1099604','Fabricação de gelo comum','II',0, 	4.5	 )
insert into Cnae values('3312102','Manutenção e reparação de aparelhos e instrumentos de medida, teste e controle','III',0, 	6	 )
insert into Cnae values('3312103','Manutenção e reparação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação','III',0, 	6	 )
insert into Cnae values('3312104','Manutenção e reparação de equipamentos e instrumentos ópticos','III',0, 	6	 )
insert into Cnae values('3313901','Manutenção e reparação de geradores, transformadores e motores elétricos','III',0, 	6	 )
insert into Cnae values('3313902','Manutenção e reparação de baterias e acumuladores elétricos, exceto para veículos','III',0, 	6	 )
insert into Cnae values('3313999','Manutenção e reparação de máquinas, aparelhos e materiais elétricos não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('3314701','Manutenção e reparação de máquinas motrizes não-elétricas','III',0, 	6	 )
insert into Cnae values('3314702','Manutenção e reparação de equipamentos hidráulicos e pneumáticos, exceto válvulas','III',0, 	6	 )
insert into Cnae values('3314703','Manutenção e reparação de válvulas industriais','III',0, 	6	 )
insert into Cnae values('3314704','Manutenção e reparação de compressores','III',0, 	6	 )
insert into Cnae values('3314705','Manutenção e reparação de equipamentos de transmissão para fins industriais','III',0, 	6	 )
insert into Cnae values('3314706','Manutenção e reparação de máquinas, aparelhos e equipamentos para instalações térmicas','III',0, 	6	 )
insert into Cnae values('3314707','Manutenção e reparação de máquinas e aparelhos de refrigeração e ventilação para uso industrial e comercial','III',0, 	6	 )
insert into Cnae values('3314708','Manutenção e reparação de máquinas, equipamentos e aparelhos para transporte e elevação de cargas','III',0, 	6	 )
insert into Cnae values('3314709','Manutenção e reparação de máquinas de escrever, calcular e de outros equipamentos não-eletrônicos para escritório','III',0, 	6	 )
insert into Cnae values('3314710','Manutenção e reparação de máquinas e equipamentos para uso geral não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('3314711','Manutenção e reparação de máquinas e equipamentos para agricultura e pecuária','III',0, 	6	 )
insert into Cnae values('3314712','Manutenção e reparação de tratores agrícolas','III',0, 	6	 )
insert into Cnae values('3314713','Manutenção e reparação de máquinas-ferramenta','III',0, 	6	 )
insert into Cnae values('3314714','Manutenção e reparação de máquinas e equipamentos para a prospecção e extração de petróleo','III',0, 	6	 )
insert into Cnae values('3314715','Manutenção e reparação de máquinas e equipamentos para uso na extração mineral, exceto na extração de petróleo','III',0, 	6	 )
insert into Cnae values('3314716','Manutenção e reparação de tratores, exceto agrícolas','III',0, 	6	 )
insert into Cnae values('3314717','Manutenção e reparação de máquinas e equipamentos de terraplenagem, pavimentação e construção, exceto tratores','III',0, 	6	 )
insert into Cnae values('3314718','Manutenção e reparação de máquinas para a indústria metalúrgica, exceto máquinas-ferramenta','III',0, 	6	 )
insert into Cnae values('3314719','Manutenção e reparação de máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo','III',0, 	6	 )
insert into Cnae values('3314720','Manutenção e reparação de máquinas e equipamentos para a indústria têxtil, do vestuário, do couro e calçados','III',0, 	6	 )
insert into Cnae values('3314721','Manutenção e reparação de máquinas e aparelhos para a indústria de celulose, papel e papelão e artefatos','III',0, 	6	 )
insert into Cnae values('3314722','Manutenção e reparação de máquinas e aparelhos para a indústria do plástico','III',0, 	6	 )
insert into Cnae values('3314799','Manutenção e reparação de outras máquinas e equipamentos para usos industriais não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('3315500','Manutenção e reparação de veículos ferroviários','III',0, 	6	 )
insert into Cnae values('3316301','Manutenção e reparação de aeronaves, exceto a manutenção na pista','III',0, 	6	 )
insert into Cnae values('3316302','Manutenção de aeronaves na pista','III',0, 	6	 )
insert into Cnae values('3317101','Manutenção e reparação de embarcações e estruturas flutuantes','III',0, 	6	 )
insert into Cnae values('3317102','Manutenção e reparação de embarcações para esporte e lazer','III',0, 	6	 )
insert into Cnae values('3319800','Manutenção e reparação de equipamentos e produtos não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('3321000','Instalação de máquinas e equipamentos industriais','III',0, 	6	 )
insert into Cnae values('4211102','Pintura para sinalização em pistas rodoviárias e aeroportos','III',0, 	6	 )
insert into Cnae values('4221903','Manutenção de redes de distribuição de energia elétrica','III',0, 	6	 )
insert into Cnae values('4221905','Manutenção de estações e redes de telecomunicações','III',0, 	6	 )
insert into Cnae values('4313400','Obras de terraplenagem','IV',0, 	4.5	 )
insert into Cnae values('4321500','Instalação e manutenção elétrica','IV',0, 	4.5	 )
insert into Cnae values('4322301','Instalações hidráulicas, sanitárias e de gás','IV',0, 	4.5	 )
insert into Cnae values('4322302','Instalação e manutenção de sistemas centrais de ar condicionado, de ventilação e refrigeração','III',0, 	6	 )
insert into Cnae values('4322303','Instalações de sistema de prevenção contra incêndio','III',0, 	6	 )
insert into Cnae values('4329101','Instalação de painéis publicitários','III',0, 	6	 )
insert into Cnae values('4329102','Instalação de equipamentos para orientação à navegação marítima, fluvial e lacustre','III',0, 	6	 )
insert into Cnae values('4329103','Instalação, manutenção e reparação de elevadores, escadas e esteiras rolantes','III',0, 	6	 )
insert into Cnae values('4329104','Montagem e instalação de sistemas e equipamentos de iluminação e sinalização em vias públicas, portos e aeroportos','III',0, 	6	 )
insert into Cnae values('4329105','Tratamentos térmicos, acústicos ou de vibração','III',0, 	6	 )
insert into Cnae values('4399102','Montagem e desmontagem de andaimes e outras estruturas temporárias','III',0, 	6	 )
insert into Cnae values('4511101','Comércio a varejo de automóveis, camionetas e utilitários novos','I',0, 	4	 )
insert into Cnae values('4520001','Serviços de manutenção e reparação mecânica de veículos automotores','III',0, 	6	 )
insert into Cnae values('4520002','Serviços de lanternagem ou funilaria e pintura de veículos automotores','III',0, 	6	 )
insert into Cnae values('4520003','Serviços de manutenção e reparação elétrica de veículos automotores','III',0, 	6	 )
insert into Cnae values('4520004','Serviços de alinhamento e balanceamento de veículos automotores','III',0, 	6	 )
insert into Cnae values('4520005','Serviços de lavagem, lubrificação e polimento de veículos automotores','III',0, 	6	 )
insert into Cnae values('4520006','Serviços de borracharia para veículos automotores','III',0, 	6	 )
insert into Cnae values('4520007','Serviços de instalação, manutenção e reparação de acessórios para veículos automotores','III',0, 	6	 )
insert into Cnae values('4520008','Serviços de capotaria','III',0, 	6	 )
insert into Cnae values('4530701','Comércio por atacado de peças e acessórios novos para veículos automotores','I',0, 	4	 )
insert into Cnae values('4541203','Comércio a varejo de motocicletas e motonetas novas','I',0, 	4	 )
insert into Cnae values('4541204','Comércio a varejo de motocicletas e motonetas usadas','I',0, 	4	 )
insert into Cnae values('4543900','Manutenção e reparação de motocicletas e motonetas','III',0, 	6	 )
insert into Cnae values('4722902','Peixaria','I',0, 	4	 )
insert into Cnae values('4729602','Comércio varejista de mercadorias em lojas de conveniência','I',0, 	4	 )
insert into Cnae values('4741500','Comércio varejista de tintas e materiais para pintura','I',0, 	4	 )
insert into Cnae values('4742300','Comércio varejista de material elétrico','I',0, 	4	 )
insert into Cnae values('4744001','Comércio varejista de ferragens e ferramentas','I',0, 	4	 )
insert into Cnae values('4744003','Comércio varejista de materiais hidráulicos','I',0, 	4	 )
insert into Cnae values('4744004','Comércio varejista de cal, areia, pedra britada, tijolos e telhas','I',0, 	4	 )
insert into Cnae values('4744005','Comércio varejista de materiais de construção não especificados anteriormente','I',0, 	4	 )
insert into Cnae values('4744006','Comércio varejista de pedras para revestimento','I',0, 	4	 )
insert into Cnae values('4744099','Comércio varejista de materiais de construção em geral','I',0, 	4	 )
insert into Cnae values('4763605','Comércio varejista de embarcações e outros veículos recreativos peças e acessórios','I',0, 	4	 )
insert into Cnae values('4771704','Comércio varejista de medicamentos veterinários','I',0, 	4	 )
insert into Cnae values('4773300','Comércio varejista de artigos médicos e ortopédicos','I',0, 	4	 )
insert into Cnae values('4789005','Comércio varejista de produtos saneantes domissanitários','I',0, 	4	 )
insert into Cnae values('4789006','Comércio varejista de fogos de artifício e artigos pirotécnicos','I',0, 	4	 )
insert into Cnae values('4789009','Comércio varejista de armas e munições','I',0, 	4	 )
insert into Cnae values('5211702','Guarda-móveis','III',0, 	6	 )
insert into Cnae values('5320201','Serviços de malote não realizados pelo Correio Nacional','III',0, 	6	 )
insert into Cnae values('5320202','Serviços de entrega rápida','III',0, 	6	 )
insert into Cnae values('5510801','Hotéis','III',0, 	6	 )
insert into Cnae values('5510802','Apart-hotéis','III',0, 	6	 )
insert into Cnae values('5510803','Motéis','III',0, 	6	 )
insert into Cnae values('5590601','Albergues, exceto assistenciais','III',0, 	6	 )
insert into Cnae values('5590602','Campings','III',0, 	6	 )
insert into Cnae values('5590603','Pensões (alojamento)','III',0, 	6	 )
insert into Cnae values('5590699','Outros alojamentos não especificados anteriormente','III',0, 	6	 )
insert into Cnae values('5620102','Serviços de alimentação para eventos e recepções – bufê','III',0, 	6	 )
insert into Cnae values('5620102','Serviços de alimentação para eventos e recepções – bufê','I',0, 	4	 )
insert into Cnae values('5811500','Edição de livros','III',0, 	6	 )
insert into Cnae values('5812301','Edição de jornais diários','III',0, 	6	 )
insert into Cnae values('5812302','Edição de jornais não diários','III',0, 	6	 )
insert into Cnae values('5813100','Edição de revistas','III',0, 	6	 )
insert into Cnae values('5819100','Edição de cadastros, listas e outros produtos gráficos','III',0, 	6	 )
insert into Cnae values('6822600','Gestão e administração da propriedade imobiliária','V',1, 	15.5	 )
insert into Cnae values('6822600','Gestão e administração da propriedade imobiliária','III',1, 	6	 )
insert into Cnae values('7711000','Locação de automóveis sem condutor','III',0, 	6	 )
insert into Cnae values('8020001','Atividades de monitoramento de sistemas de segurança eletrônico','IV',0, 	4.5	 )
insert into Cnae values('8219901','Fotocópias','III',0, 	6	 )
insert into Cnae values('8599601','Formação de condutores','III',0, 	6	 )
insert into Cnae values('8599602','Cursos de pilotagem','III',0, 	6	 )
insert into Cnae values('8610102','Atividades de atendimento em pronto-socorro e unidades hospitalares para atendimento a urgências','III',1, 	6	 )
insert into Cnae values('8621601','UTI móvel','III',1, 	6	 )
insert into Cnae values('8621602','Serviços móveis de atendimento a urgências, exceto por UTI móvel','III',1, 	6	 )
insert into Cnae values('8622400','Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências','V',1, 	15.5	 )
insert into Cnae values('8690902','Atividades de banco de leite humano','III',1, 	6	 )
insert into Cnae values('8711501','Clínicas e residências geriátricas','V',1, 	15.5	 )
insert into Cnae values('8711502','Instituições de longa permanência para idosos','III',0, 	6	 )
insert into Cnae values('8712300','Atividades de fornecimento de infra-estrutura de apoio e assistência a paciente no domicílio','III',0, 	6	 )
insert into Cnae values('9003500','Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas','III',0, 	6	 )
insert into Cnae values('9101500','Atividades de bibliotecas e arquivos','III',0, 	6	 )
insert into Cnae values('9102301','Atividades de museus e de exploração de lugares e prédios históricos e atrações similares','III',0, 	6	 )
insert into Cnae values('9102302','Restauração e conservação de lugares e prédios históricos','III',0, 	6	 )
insert into Cnae values('6612605','Agentes de investimentos em aplicações financeiras','III',0, 	6	 )
insert into Cnae values('6911702','Atividades auxiliares da justiça','III',0, 	6	 )


