USE [SIS_TECH]
GO


insert into TipoPessoa values('Pessoa Física')
insert into TipoPessoa values('Pessoa Jurídica')

insert into TipoEndereco values('Comercial')
insert into TipoEndereco values('Residencial')
insert into TipoEndereco values('Cobrança')
insert into TipoEndereco values('Outros')

insert into TipoContato values('Comercial')
insert into TipoContato values('Residencial')
insert into TipoContato values('Cobrança')
insert into TipoContato values('Outros')

insert into TipoCCT values('Sindhosvet')
insert into TipoCCT values('Serviços')
insert into TipoCCT values('Comércio')

insert into StatusCCT values('Assinada')
insert into StatusCCT values('Em Negociação Pacífica')
insert into StatusCCT values('Em Negociação Jurídica')


insert into RamoAtividade values('Alimentos e Bebidas')
insert into RamoAtividade values('Arte e Antiguidades')
insert into RamoAtividade values('Artigos Religiosos')
insert into RamoAtividade values('Assinaturas e Revistas')
insert into RamoAtividade values('Automóveis e Veículos')
insert into RamoAtividade values('Bebês e Cia')
insert into RamoAtividade values('Blu-Ray')
insert into RamoAtividade values('Brindes / Materiais Promocionais')
insert into RamoAtividade values('Brinquedos e Games')
insert into RamoAtividade values('Casa e Decoração')
insert into RamoAtividade values('CDs')
insert into RamoAtividade values('Colecionáveis')
insert into RamoAtividade values('Compras Coletivas')
insert into RamoAtividade values('Construção e Ferramentas')
insert into RamoAtividade values('Cosméticos e Perfumaria')
insert into RamoAtividade values('Cursos e Educação')
insert into RamoAtividade values('Discos de Vinil')
insert into RamoAtividade values('DVDs')
insert into RamoAtividade values('Eletrodomésticos')
insert into RamoAtividade values('Eletrônicos')
insert into RamoAtividade values('Emissoras de Rádio')
insert into RamoAtividade values('Emissoras de Televisão')
insert into RamoAtividade values('Empregos')
insert into RamoAtividade values('Empresas de Telemarketing')
insert into RamoAtividade values('Esporte e Lazer')
insert into RamoAtividade values('Fitas K7 Gravadas')
insert into RamoAtividade values('Flores, Cestas e Presentes')
insert into RamoAtividade values('Fotografia')
insert into RamoAtividade values('HD-DVD')
insert into RamoAtividade values('Igrejas / Templos / Instituições Religiosas')
insert into RamoAtividade values('Indústria, Comércio e Negócios')
insert into RamoAtividade values('Infláveis Promocionais')
insert into RamoAtividade values('Informática')
insert into RamoAtividade values('Ingressos')
insert into RamoAtividade values('Instrumentos Musicais')
insert into RamoAtividade values('Joalheria')
insert into RamoAtividade values('Lazer')
insert into RamoAtividade values('LD')
insert into RamoAtividade values('Livros')
insert into RamoAtividade values('MD')
insert into RamoAtividade values('Moda e Acessórios')
insert into RamoAtividade values('Motéis')
insert into RamoAtividade values('Música Digital')
insert into RamoAtividade values('Natal')
insert into RamoAtividade values('Negócios e Oportunidades')
insert into RamoAtividade values('Outros Serviços')
insert into RamoAtividade values('Outros Serviços de Avaliação')
insert into RamoAtividade values('Papelaria e Escritório')
insert into RamoAtividade values('Páscoa')
insert into RamoAtividade values('Pet Shop')
insert into RamoAtividade values('Saúde')
insert into RamoAtividade values('Serviço Advocaticios')
insert into RamoAtividade values('Serviço de Distribuição de Jornais / Revistas')
insert into RamoAtividade values('Serviços Administrativos')
insert into RamoAtividade values('Serviços Artísticos')
insert into RamoAtividade values('Serviços de Abatedouros / Matadouros')
insert into RamoAtividade values('Serviços de Aeroportos')
insert into RamoAtividade values('Serviços de Agências')
insert into RamoAtividade values('Serviços de Aluguel / Locação')
insert into RamoAtividade values('Serviços de Armazenagem')
insert into RamoAtividade values('Serviços de Assessorias')
insert into RamoAtividade values('Serviços de Assistência Técnica / Instalações ')
insert into RamoAtividade values('Serviços de Associações')
insert into RamoAtividade values('Serviços de Bancos de Sangue')
insert into RamoAtividade values('Serviços de Bibliotecas')
insert into RamoAtividade values('Serviços de Cartórios')
insert into RamoAtividade values('Serviços de Casas Lotéricas')
insert into RamoAtividade values('Serviços de Confecções')
insert into RamoAtividade values('Serviços de Consórcios')
insert into RamoAtividade values('Serviços de Consultorias')
insert into RamoAtividade values('Serviços de Cooperativas')
insert into RamoAtividade values('Serviços de Despachante')
insert into RamoAtividade values('Serviços de Engenharia')
insert into RamoAtividade values('Serviços de Estacionamentos')
insert into RamoAtividade values('Serviços de Estaleiros')
insert into RamoAtividade values('Serviços de Exportação / Importação')
insert into RamoAtividade values('Serviços de Geólogos')
insert into RamoAtividade values('Serviços de joalheiros')
insert into RamoAtividade values('Serviços de Leiloeiros')
insert into RamoAtividade values('Serviços de limpeza')
insert into RamoAtividade values('Serviços de Loja de Conveniência')
insert into RamoAtividade values('Serviços de Mão de Obra')
insert into RamoAtividade values('Serviços de Órgão Públicos')
insert into RamoAtividade values('Serviços de Pesquisas')
insert into RamoAtividade values('Serviços de Portos')
insert into RamoAtividade values('Serviços de Saúde / Bem Estar')
insert into RamoAtividade values('Serviços de Seguradoras')
insert into RamoAtividade values('Serviços de Segurança')
insert into RamoAtividade values('Serviços de Sinalização')
insert into RamoAtividade values('Serviços de Sindicatos / Federações')
insert into RamoAtividade values('Serviços de Traduções')
insert into RamoAtividade values('Serviços de Transporte')
insert into RamoAtividade values('Serviços de Utilidade Pública')
insert into RamoAtividade values('Serviços em Agricultura / Pecuária / Piscicultura')
insert into RamoAtividade values('Serviços em Alimentação')
insert into RamoAtividade values('Serviços em Arte')
insert into RamoAtividade values('Serviços em Cine / Foto / Som')
insert into RamoAtividade values('Serviços em Comunicação')
insert into RamoAtividade values('Serviços em Construção')
insert into RamoAtividade values('Serviços em Ecologia / Meio Ambiente')
insert into RamoAtividade values('Serviços em Eletroeletrônica / Metal Mecânica')
insert into RamoAtividade values('Serviços em Festas / Eventos')
insert into RamoAtividade values('Serviços em Informática')
insert into RamoAtividade values('Serviços em Internet')
insert into RamoAtividade values('Serviços em Jóias / Relógios / Óticas')
insert into RamoAtividade values('Serviços em Telefonia')
insert into RamoAtividade values('Serviços em Veículos')
insert into RamoAtividade values('Serviços Esotéricos / Místicos')
insert into RamoAtividade values('Serviços Financeiros')
insert into RamoAtividade values('Serviços Funerários')
insert into RamoAtividade values('Serviços Gerais')
insert into RamoAtividade values('Serviços Gráficos / Editoriais')
insert into RamoAtividade values('Serviços para Animais')
insert into RamoAtividade values('Serviços para Deficientes')
insert into RamoAtividade values('Serviços para Escritórios')
insert into RamoAtividade values('Serviços para Roupas')
insert into RamoAtividade values('Serviços Socias / Assistenciais')
insert into RamoAtividade values('Sex Shop')
insert into RamoAtividade values('Shopping Centers')
insert into RamoAtividade values('Tabacaria')
insert into RamoAtividade values('Tarifas Bancárias')
insert into RamoAtividade values('Tarifas Telefônicas')
insert into RamoAtividade values('Telefonia')
insert into RamoAtividade values('Turismo')



